name = "TuringCLIExample"
uuid = "843339f9-e47f-46d2-a0d4-2bfd543a186f"
authors = ["Jesse Perla <jesseperla@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
TuringCallbacks = "ea0860ee-d0ef-45ef-82e6-cc37d6be2f9c"

[compat]
julia = "1.6"
